/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dbms.ui;

import com.mycompany.dbms.datastructures.table.Table;
import com.mycompany.dbms.datastructures.trees.BTree;
import com.mycompany.dbms.datastructures.list.*;
import com.mycompany.dbms.datastructures.table.Input;
import com.mycompany.dbms.datastructures.table.Register;
import com.mycompany.dbms.datastructures.table.Validator;
import com.mycompany.dbms.datastructures.trees.NodeLeaf;
import com.mycompany.dbms.files.Xml;
import java.awt.Font;
import java.io.File;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhony
 */
public class Main extends javax.swing.JFrame {
    
    DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel() ;
    DefaultComboBoxModel modeloTabla = new DefaultComboBoxModel() ;
    DefaultTableModel n =  new DefaultTableModel();
    DefaultTableModel n2 =  new DefaultTableModel();    
    private BTree Tree;
    private SimpleList TableRegistres = new SimpleList();
    private SimpleList Campos = new SimpleList();
    private Table CurrentTable;
    
    public Main() {
        
        this.Tree = new BTree();
        initComponents();
        Form.setLayout(new javax.swing.BoxLayout(Form, BoxLayout.Y_AXIS));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JTabbedPane();
        Add = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameRegistro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NameTable = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Registros = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        Tipo = new javax.swing.JComboBox<>();
        Delete = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Tablas = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        Form = new javax.swing.JPanel();
        AddButton = new javax.swing.JButton();
        Update = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TableDelete = new javax.swing.JComboBox<>();
        DeleteButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ButtonDelete = new javax.swing.JButton();
        ValueDelete = new javax.swing.JTextField();
        PKName = new javax.swing.JLabel();
        Report = new javax.swing.JPanel();
        Archive = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        FileErrors = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        TableData = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TableSearch = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        SearchCombo = new javax.swing.JComboBox<>();
        SearchValue = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TSearch = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Registros");

        NameRegistro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("Agregar Registro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Nombre Tabla");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Tipo");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Llave Primaria");

        NameTable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        NameTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTableActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Nombre");

        Registros.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Registros.setModel(modeloCombo);
        Registros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrosActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setText("Crear Tabla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Tipo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "int", "string","char","double","boolean" }));

        javax.swing.GroupLayout AddLayout = new javax.swing.GroupLayout(Add);
        Add.setLayout(AddLayout);
        AddLayout.setHorizontalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AddLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(48, 48, 48)
                                .addComponent(NameRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jButton2))
                    .addGroup(AddLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(62, 62, 62)
                        .addComponent(NameTable, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addGroup(AddLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(Registros, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        AddLayout.setVerticalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NameTable, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)))
                .addGap(82, 82, 82)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jButton2))
        );

        Menu.addTab("Ingresar Tabla", Add);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Tabla");

        Tablas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Tablas.setModel(modeloTabla);

        jButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton3.setText("Cargar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormLayout = new javax.swing.GroupLayout(Form);
        Form.setLayout(FormLayout);
        FormLayout.setHorizontalGroup(
            FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        FormLayout.setVerticalGroup(
            FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        AddButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AddButton.setText("Ingresar");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeleteLayout = new javax.swing.GroupLayout(Delete);
        Delete.setLayout(DeleteLayout);
        DeleteLayout.setHorizontalGroup(
            DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317))
            .addGroup(DeleteLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteLayout.createSequentialGroup()
                        .addComponent(Tablas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton3))
                    .addComponent(Form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        DeleteLayout.setVerticalGroup(
            DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Tablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(Form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(AddButton)
                .addGap(30, 30, 30))
        );

        Menu.addTab("Cargar Dato", Delete);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Tabla");

        TableDelete.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TableDelete.setModel(modeloTabla);

        DeleteButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DeleteButton.setText("Cargar");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Llave Primaria");

        ButtonDelete.setText("Eliminar");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ValueDelete.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        PKName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PKName.setText(".");

        javax.swing.GroupLayout UpdateLayout = new javax.swing.GroupLayout(Update);
        Update.setLayout(UpdateLayout);
        UpdateLayout.setHorizontalGroup(
            UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(UpdateLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(UpdateLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TableDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateLayout.createSequentialGroup()
                        .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(PKName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addComponent(ValueDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        UpdateLayout.setVerticalGroup(
            UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TableDelete)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValueDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PKName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(218, 218, 218)
                .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        Menu.addTab("Eliminar", Update);

        javax.swing.GroupLayout ReportLayout = new javax.swing.GroupLayout(Report);
        Report.setLayout(ReportLayout);
        ReportLayout.setHorizontalGroup(
            ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        ReportLayout.setVerticalGroup(
            ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        Menu.addTab("Reporte", Report);

        jButton4.setText("Cargar Archivo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        FileErrors.setColumns(20);
        FileErrors.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        FileErrors.setRows(5);
        jScrollPane3.setViewportView(FileErrors);

        javax.swing.GroupLayout ArchiveLayout = new javax.swing.GroupLayout(Archive);
        Archive.setLayout(ArchiveLayout);
        ArchiveLayout.setHorizontalGroup(
            ArchiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArchiveLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(ArchiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        ArchiveLayout.setVerticalGroup(
            ArchiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArchiveLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        Menu.addTab("Archivo", Archive);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Tabla");

        jButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton5.setText("Cargar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        TableData.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TableData.setModel(modeloTabla);
        TableData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(TableData, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TableData))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        Menu.addTab("Datos", jPanel1);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("Tabla");

        TableSearch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TableSearch.setModel(modeloTabla);
        TableSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableSearchActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jButton6.setText("Cargar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jButton7.setText("Buscar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("Dato a Buscar:");

        SearchCombo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        SearchValue.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SearchValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchValueActionPerformed(evt);
            }
        });

        TSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TSearch);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(SearchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(TableSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(SearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TableSearch))
                .addGap(51, 51, 51)
                .addComponent(jLabel11)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        Menu.addTab("Buscar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       if(!NameTable.getText().isEmpty()){
            Table T = new Table(NameTable.getText(),String.valueOf(Registros.getSelectedItem()),TableRegistres,Registros.getSelectedIndex());
            System.out.println("VALOR DEL INDEX: " + T.getIndexPKey());
            if(!Tree.Add(T))JOptionPane.showMessageDialog(this, "Ya existe una tabla con el nombre: " + NameTable.getText(), "Error", HEIGHT);
            else{
                TableRegistres = new SimpleList();
                modeloTabla.addElement(NameTable.getText());
                modeloCombo.removeAllElements();
            }
        }else JOptionPane.showMessageDialog(this, "El nombre de la tabla esta vacio", "Error", HEIGHT);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Model = NameRegistro.getText();
        if(!Model.isEmpty()){
            Node tmp;
            Register T = new Register(NameRegistro.getText(),String.valueOf(Tipo.getSelectedItem()));
            tmp = new Node(T);
            TableRegistres.Add(tmp);
            modeloCombo.addElement(NameRegistro.getText());
        }
        else JOptionPane.showMessageDialog(this, "El nombre esta vacio", "Error de Registro", HEIGHT);
        
        NameRegistro.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       JFileChooser fileChosser = new JFileChooser();
        int seleccion = fileChosser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fileChosser.getSelectedFile();
            System.out.println("ARCHIVO LEIDO");
            Xml.Read(fichero,Tree,modeloTabla,FileErrors);
        }else JOptionPane.showMessageDialog(this,"Error al Leer el Archivo");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Campos = new SimpleList();
        Form.removeAll();
        Form.revalidate();
        Form.repaint();
        String NameTable = String.valueOf(Tablas.getSelectedItem());
        CurrentTable = (Table)Tree.Search(NameTable);
        if(CurrentTable != null){
            Node tmp = CurrentTable.getColumns().getRoot();
            for (int i = 0; i <CurrentTable.getColumns().getIndex(); i++) {
                Register tmp2 = (Register) tmp.getValue();
                JLabel Name = new JLabel(tmp2.getNombre());
                JTextField Value = new JTextField(15);
                Font font = new Font(Value.getFont().getName(),Font.PLAIN,16);
                Name.setFont(font);
                Value.setFont(font);
                Form.add(Name);
                Form.add(Value);
                Campos.Add(new Node(Value));
                Form.revalidate();
                Form.repaint();
                tmp = tmp.getNext();
            }
        }else JOptionPane.showMessageDialog(this,"No hay tablas creadas");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       String Name = String.valueOf(TableData.getSelectedItem());
       Table T = (Table)Tree.Search(Name);
       if(T!= null){
        setModel(T,Table,n);
        setData(T,n);
       }else JOptionPane.showMessageDialog(this,"No hay tablas creadas");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        if(CurrentTable != null){
        Node tmp = Campos.getRoot();
        Input input = new Input(CurrentTable.getNumberColumns(),CurrentTable.getIndexPKey());
        for (int i = 0; i < Campos.getIndex(); i++) {
            JTextField tmp2 = (JTextField) tmp.getValue();
            String Data = tmp2.getText();
            input.getData()[i] = Data;
            tmp = tmp.getNext();
        }
            if(Validator.Compare(input, CurrentTable.getColumns())) {
                if(!CurrentTable.Add(input)) JOptionPane.showMessageDialog(this,"Ya existe un dato con el valor con el mismo valor");;
            }
            else JOptionPane.showMessageDialog(this,"Los tipos de datos no coinciden");
        }else JOptionPane.showMessageDialog(this,"No hay Tablas");
        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        Table T = (Table) Tree.Search(String.valueOf(TableDelete.getSelectedItem()));
        if(T!= null)
        PKName.setText(T.getPrimaryKey());
        else JOptionPane.showMessageDialog(this, "Seleccione una tabla", "ERROR", HEIGHT);
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        Table T = (Table) Tree.Search(String.valueOf(TableDelete.getSelectedItem()));
        if(T!= null){
            BTree tmp = T.getRecords();
            if(!ValueDelete.getText().isEmpty()){
                String Value = ValueDelete.getText();
                tmp.Delete(Value);
            }
            else JOptionPane.showMessageDialog(this, "Campo Vacio", "ERROR", HEIGHT);
        }else JOptionPane.showMessageDialog(this, "No hay tablas", "ERROR", HEIGHT);
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void TableSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TableSearchActionPerformed

    private void TableDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TableDataActionPerformed

    private void NameTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTableActionPerformed

    private void RegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrosActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Table T = (Table) Tree.Search(String.valueOf(TableSearch.getSelectedItem()));
        if(T!= null){
            DefaultComboBoxModel modeloCombo1 = new DefaultComboBoxModel() ;
            SimpleList  tmp = T.getColumns();
            Node tmp2 = tmp.getRoot();
            for (int i = 0; i <tmp.getIndex(); i++) {
                Register R = (Register) tmp2.getValue();
                modeloCombo1.addElement(R.getNombre());
                tmp2 = tmp2.getNext();
            }
            SearchCombo.setModel(modeloCombo1);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void SearchValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchValueActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Table T = (Table) Tree.Search(String.valueOf(TableSearch.getSelectedItem()));
        if(T!= null){
            setModel(T,TSearch,n2);
            
            BTree Datos = T.getRecords();
            Object[] Datos1 = new Object[n2.getColumnCount()];
            n2.setRowCount(0);
            String Key = String.valueOf(SearchCombo.getSelectedItem());
            if(Key.equals(T.getPrimaryKey())){
                Input tmp = (Input) Datos.Search(SearchValue.getText());
                if(tmp!= null){
                    for (int i = 0; i <tmp.getData().length; i++) {
                        System.out.println("Agregando: " + tmp.getData()[i]);
                        Datos1[i] = tmp.getData()[i];
                    }
                    n2.addRow(Datos1);
                    TSearch.setModel(n2);
                }else JOptionPane.showMessageDialog(this,"No se encontro el elemento");
            }else{
                System.out.println("BUSCANDO POR: " + Key);
                int K = T.getColumns().getIndex(Key);
                SimpleList List = Datos.SearchByTag(K, SearchValue.getText());
                Node tmp = List.getRoot();
                while(tmp != null){
                    for (int i = 0; i <T.getNumberColumns(); i++) {
                        Input tmp2 = (Input) tmp.getValue();
                        Datos1[i] = tmp2.getData()[i];
                    }
                    n2.addRow(Datos1);
                    TSearch.setModel(n2);
                    tmp = tmp.getNext();
                }
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed
    
    public void setModel(Table T,JTable Table,DefaultTableModel n){
        String[] Nombre = new String[T.getNumberColumns()];
        Node tmp = T.getColumns().getRoot();
        for (int i = 0; i <Nombre.length; i++) {
            Register tmp2 = (Register) tmp.getValue();
            Nombre[i] = tmp2.getNombre();
            tmp = tmp.getNext();
        }
        n.setColumnIdentifiers(Nombre);
        Table.setModel(n);
    }
    
    private void setData(Table T,DefaultTableModel n){
        BTree Datos = T.getRecords();
        Object[] Datos1 =  new Object[n.getColumnCount()];
        n.setRowCount(0);
        NodeLeaf tmp = Datos.NodeInitial();
        while(tmp != null){
            for (int i = 0; i <tmp.getIndex(); i++) {
                Input tmp2 = (Input) tmp.getValue()[i];
                for (int j = 0; j < T.getNumberColumns(); j++) {
                    Datos1[j] = tmp2.getData()[j];
                }
                n.addRow(Datos1);
            }
            tmp = tmp.getNext();
        }
        Table.setModel(n);
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add;
    private javax.swing.JButton AddButton;
    private javax.swing.JPanel Archive;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JPanel Delete;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextArea FileErrors;
    private javax.swing.JPanel Form;
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JTextField NameRegistro;
    private javax.swing.JTextField NameTable;
    private javax.swing.JLabel PKName;
    private javax.swing.JComboBox<String> Registros;
    private javax.swing.JPanel Report;
    private javax.swing.JComboBox<String> SearchCombo;
    private javax.swing.JTextField SearchValue;
    private javax.swing.JTable TSearch;
    private javax.swing.JComboBox<String> Tablas;
    private javax.swing.JTable Table;
    private javax.swing.JComboBox<String> TableData;
    private javax.swing.JComboBox<String> TableDelete;
    private javax.swing.JComboBox<String> TableSearch;
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JPanel Update;
    private javax.swing.JTextField ValueDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
